baseURL = "https://ak523.github.io/Whoami/public/"
languageCode = "en-us"
title = 'Club Gamma Open Source'
theme = "pulp"

[taxonomies]
  series = "series"

[params]
    author = "🌷🤩Livsnjutare🌙♒"
    avatar = "logo.jpeg"
    favicon = "aquarius-16.png"
    
    publicationYear = "2021"

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    identifier = "contributors"
    pre = "<i class='fa fa-edit fa-lg'></i>"
    url = "./contributors"
    weight = 1


[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/Hetvi07/"
    weight = 30


[[menu.main]]
    identifier = "linkedin"
    # name = "LinkedIn"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"
    url = "https://www.linkedin.com/in/hetvi07/"
    weight = 32
[[menu.main]]
    identifier = "instagram"
    # name = "Instagram"
    pre = "<i class='fab fa-instagram fa-lg'></i>"
    url = "https://www.instagram.com/hadvanihetvi/"
    weight = 33


